### ISSUE TITLE
cas broken at runtime since #16

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra-cas-server#21]
after #16, it seems "something" in the oidc bits expects a writable path that isnt allowed to the tomcat user:
```
<2>Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.oidcJsonWebKeystoreGeneratorService' defined in class path resource [org/apereo/cas/oidc/config/OidcConfiguration.class]: Invocation of init method failed; nested exception is java.io.IOException: Directory '/etc/cas/config' could not be created
...
<2>Caused by: java.io.IOException: Directory '/etc/cas/config' could not be created
<2>    at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2436)
<2>    at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3356)
<2>    at org.apache.commons.io.FileUtils.write(FileUtils.java:3034)
<2>    at org.apache.commons.io.FileUtils.write(FileUtils.java:3017)
<2>    at org.apereo.cas.oidc.jwks.generator.OidcDefaultJsonWebKeystoreGeneratorService.generate(OidcDefaultJsonWebKeystoreGeneratorService.java:57)
<2>    at org.apereo.cas.oidc.jwks.generator.OidcDefaultJsonWebKeystoreGeneratorService.generate(OidcDefaultJsonWebKeystoreGeneratorService.java:39)
<2>    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
<2>    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
<2>    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
<2>    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
<2>    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1920)
<2>    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)
<2>    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)

```

**Comment by landryb** [comment]
my understanding of https://apereo.github.io/cas/6.5.x/authentication/OIDC-Authentication-JWKS-Storage.html is that it needs a writable path for `cas.authn.oidc.jwks.file-system.jwks-file` even if oidc isnt used

**Comment by landryb** [comment]
found it in the docker-master branch of https://github.com/georchestra/datadir/blob/docker-master/cas/config/cas.properties#L50

*sigh* .. yet another example that nobody tests the non-docker case anymore :(

**Comment by pmauduit** [comment]
sorry about this one ...

**Comment by edevosc2c** [comment]
> found it in the docker-master branch of [georchestra/datadir@`docker-master`/cas/config/cas.properties#L50](https://github.com/georchestra/datadir/blob/docker-master/cas/config/cas.properties?rgh-link-date=2023-12-06T10%3A49%3A22Z#L50)
> 
> _sigh_ .. yet another example that nobody tests the non-docker case anymore :(

I would say yet another example for having a single branch shared for both non-docker and docker stuff :)!

**Comment by landryb** [comment]
> I would say yet another example for having a single branch shared for both non-docker and docker stuff :)!

trolling aside, can't agree more, but if you go that way *please* test the non-docker case.

**Comment by edevosc2c** [comment]
> > I would say yet another example for having a single branch shared for both non-docker and docker stuff :)!
> 
> trolling aside, can't agree more, but if you go that way _please_ test the non-docker case.

That was not trolling, it's serious. That's something we aspire to do.
